### ISSUE TITLE
Should we fit the pixel scaled or "raw" DN values out of splat?

### ISSUE THREAD

**Issue by jeanconn** [sot/anneal_pathfinder#26]
I think we went back and forth on this during the pathfinder.  The scaled values go negative, but are the same as the values we just fit in the notebook.

**Comment by taldcroft** [comment]
I believe we should use the methodology in the notebook and what was successfully used during the 2015 pathfinder.

**Comment by jeanconn** [comment]
I thought we had trouble with some of the negative values during the
pathfinder.
​

**Comment by taldcroft** [comment]
It would be reasonable to replace negative values with a small value like 1.0.

**Comment by jeanconn** [comment]
At the point where we're replacing values, I think we might as well reject the scaling.  I assume for the notebook, the negative values were no big deal as in the post-facto analysis, there were a lot more positive values.  I assume that would also be true during the activity, but I don't know how a warm pixel might get screwed up.  I thought that we ended up rejecting too many pixels and fits last time due to this kind of weirdness, but I'll review the data.

According to splat, the scale is "DN = (scale_factor/32 \* pixsig - 50)".  

![scale_no_scale](https://cloud.githubusercontent.com/assets/791508/18398157/72ff866e-7699-11e6-8416-00b446151ee4.png)

**Comment by taldcroft** [comment]
Anyway I'm a little confused because for model evaluation and fitting I don't see any obvious problem with negative data points.  I do recall seeing bogus / bad fit values in the logs before we got any warm temperature data.  I don't remember why this was.

Your plot example which peaks at ~60 DN is not one we would focus on in any case.  Warm/hot pixels are interesting.

**Comment by jeanconn** [comment]
> Your plot example which peaks at ~60 DN is not one we would focus on in any case. Warm/hot pixels are interesting.

I'll recheck my work.  I thought this was one of our warm pixels (after DN \* gain / integ time).

**Comment by jeanconn** [comment]
This is a plot of slot 7 pix 18 (in the notebook numbering) so this was one of our two good ones for the scale fit.

**Comment by taldcroft** [comment]
OK, the units threw me off.

**Comment by jeanconn** [comment]
> Anyway I'm a little confused because for model evaluation and fitting I don't see any obvious problem with negative data points.

I just thought that negative points just really didn't make sense for our model, because I really don't expect that if a pixel has a value of -28 (e-/sec) at -19 that it will have a value of -2555 at +15C.  But as you say, maybe for scale fitting, it makes no difference.

**Comment by taldcroft** [comment]
What we care about most is getting a fitted value for the dark current scale factor from -19C to +15C.  I'm not sure in what context we would apply that scale factor to a single pixel readout from -19C (or -14C), that doesn't have much practical value as far as I can tell.  Is the code doing this somewhere?  (Usually your questions have a basis!).

**Comment by jeanconn** [comment]
> What we care about most is getting a fitted value for the dark current
> scale factor from -19C to +15C. I'm not sure in what context we would apply
> that scale factor to a single pixel readout from -19C (or -14C), that
> doesn't have much practical value as far as I can tell. Is the code doing
> this somewhere? (Usually your questions have a basis!).
> 
> ​Fair enough.  I wasn't particularly focused on the scale factor as applied
> to a particular readout, but when I tried to think through "what the scale
> factor means and how we model it to fit these data correctly" I couldn't
> wrap my brain around negative values introduced by a (I assume bad) bias
> correction in the pixel scaling of these input data.   When you say " I'm
> not sure in what context we would apply that scale factor to a single pixel
> readout from -19C (or -14C)," I get a little confused, because I thought
> that's kinda what sherpa is doing, in aggregate, to fit these data.

But, it probably makes sense for me to just take a quick look at the fit
data we had from the pathfinder and see why some of the fits were bad
instead of starting from some kind of first principles approach to count
data here.
